# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: duongnguyen16.ccat
PackageVersion: 26.10.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ccat.exe
  PortableCommandAlias: ccat
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/duongnguyen16/ccat/releases/download/v26.10.1/ccat-v26.10.1-x86_64-windows.zip
  InstallerSha256: 1B2A883D284D7AEF9DDA920E035BF4C92A5288EE3829BB4E92630474ED4339ED
ManifestType: installer
ManifestVersion: 1.10.0
